### PR TITLE
647 - bug - netapp-ontap_snapmirror_policy resource

### LINKED ISSUE #647: [Bug]: snapmirror_policy resource: "Provider produced inconsistent result" when retention is null but API returns default retention rule
### Terraform Core Version

v1.14.7

### ONTAP Provider Version

2.3.0

### Affected Resource(s)

When creating a netapp-ontap_snapmirror_policy resource without specifying retention, the provider returns an error because:

The plan shows retention as null
After creation, the API returns a default retention rule [{count: 1, label: "sm_created"}]
Terraform detects this as an inconsistent result

### Expected Behavior

It should go through

### Actual Behavior

When creating a netapp-ontap_snapmirror_policy resource without specifying retention, the provider returns an error because:

The plan shows retention as null
After creation, the API returns a default retention rule [{count: 1, label: "sm_created"}]
Terraform detects this as an inconsistent result

### Relevant Error/Panic Output Snippet

```shell
sshashi@sshashi-mac-1 12-snapmirror-policy % terraform apply  
╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI configuration:
│  - netapp/netapp-ontap in /Users/sshashi/go/bin
│ 
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become
│ incompatible with published releases.
╵
data.netapp-ontap_svms.pool: Reading...
data.netapp-ontap_svms.pool: Read complete after 6s

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
<= read (data resources)

Terraform will perform the following actions:

  # data.netapp-ontap_snapmirror_policies.filtered will be read during apply
  # (depends on a resource or a module with changes pending)
<= data "netapp-ontap_snapmirror_policies" "filtered" {
      + cx_profile_name     = "gcnv-ontap-mode"
      + filter              = {
          + name = "tf_ontap_mode_sm_policy4"
        }
      + snapmirror_policies = (known after apply)
    }

  # data.netapp-ontap_snapmirror_policy.single will be read during apply
  # (depends on a resource or a module with changes pending)
<= data "netapp-ontap_snapmirror_policy" "single" {
      + comment                     = (known after apply)
      + copy_all_source_snapshots   = (known after apply)
      + copy_latest_source_snapshot = (known after apply)
      + create_snapshot_on_source   = (known after apply)
      + cx_profile_name             = "gcnv-ontap-mode"
      + id                          = (known after apply)
      + identity_preservation       = (known after apply)
      + name                        = "tf_ontap_mode_sm_policy4"
      + network_compression_enabled = (known after apply)
      + retention                   = (known after apply)
      + svm_name                    = (known after apply)
      + sync_type                   = (known after apply)
      + transfer_schedule_name      = (known after apply)
      + type                        = (known after apply)
    }

  # netapp-ontap_snapmirror_policy.test will be created
  + resource "netapp-ontap_snapmirror_policy" "test" {
      + comment                     = "Terraform ontap-mode test policy"
      + copy_all_source_snapshots   = false
      + copy_latest_source_snapshot = false
      + create_snapshot_on_source   = false
      + cx_profile_name             = "gcnv-ontap-mode"
      + id                          = (known after apply)
      + name                        = "tf_ontap_mode_sm_policy4"
      + network_compression_enabled = false
      + svm_name                    = "gcnv-37daae66d51a0bc-svm-01"
      + type                        = "async"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + policy_comment_from_ds    = (known after apply)
  + policy_type_from_ds       = (known after apply)
  + snapmirror_policies_count = (known after apply)
  + snapmirror_policy_name    = "tf_ontap_mode_sm_policy4"
  + svm_name                  = "gcnv-37daae66d51a0bc-svm-01"

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

netapp-ontap_snapmirror_policy.test: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to netapp-ontap_snapmirror_policy.test, provider "provider[\"registry.terraform.io/netapp/netapp-ontap\"]"
│ produced an unexpected new value: .retention: was null, but now
│ cty.ListVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"count":cty.NumberIntVal(1),
│ "creation_schedule_name":cty.NullVal(cty.String), "label":cty.StringVal("sm_created"), "prefix":cty.NullVal(cty.String)})}).
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

### Terraform Configuration Files

[12-snapmirror-policy.zip](https://github.com/user-attachments/files/26200460/12-snapmirror-policy.zip)

### Steps to Reproduce

Steps to Reproduce:

Create a Terraform configuration with a netapp-ontap_snapmirror_policy resource without specifying the retention attribute:
resource "netapp-ontap_snapmirror_policy" "test" {
  cx_profile_name             = "your-connection-profile"
  name                        = "tf_test_policy"
  svm_name                    = "your-svm-name"
  type                        = "async"
  comment                     = "Test policy"
  network_compression_enabled = false
  # Note: retention is NOT specified
}
Run terraform plan - the plan shows retention as null

Run terraform apply

Error occurs:

Error: Provider produced inconsistent result after apply
When applying changes to netapp-ontap_snapmirror_policy.test, provider 
produced an unexpected new value: .retention: was null, but now 
cty.ListVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"count":cty.NumberIntVal(1),
"creation_schedule_name":cty.NullVal(cty.String), "label":cty.StringVal("sm_created"), 
"prefix":cty.NullVal(cty.String)})}).
Expected Behavior:

The resource should be created successfully, with the provider handling the default retention rule that ONTAP automatically adds.

Actual Behavior:

Terraform fails with "Provider produced inconsistent result" because the API returns a default retention rule [{count: 1, label: "sm_created"}] that wasn't in the plan.

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by csahu9**
Issue https://github.com/NetApp/terraform-provider-netapp-ontap/issues/647

fixed issue with create operation when `retention` is not set in config

```
[root@scs000952326 snapmirror]# TF_ACC=1 go test `go list ./... | grep -e provider` -v -run=TestAccSnapmirrorPolicyResource
=== RUN   TestAccSnapmirrorPolicyResourceAlias
--- PASS: TestAccSnapmirrorPolicyResourceAlias (44.33s)
=== RUN   TestAccSnapmirrorPolicyResource
--- PASS: TestAccSnapmirrorPolicyResource (44.19s)
PASS
ok      github.com/netapp/terraform-provider-netapp-ontap/internal/provider/snapmirror  88.542s
```

### CODE REVIEW

**Review by chuyich — COMMENTED** [review]
Would you please update the CHANGELOG? Also please fix the failed checks.

**Comment by csahu9** [comment]
> Would you please update the CHANGELOG? Also please fix the failed checks.

hi @chuyich 
I've updated the release notes.
After updating the version as 2.5.1 in bd_scan file, blackduck scan build succeeded.

However, what to do for the missing doc error?
```
The following documentation files are missing:
docs/data-sources/volume_files.md
```

**Comment by chuyich** [comment]
@csahu9 The error is based on .github/workflows/check_for_documentation.yml 
It checked the .go file name and check the doc file accordingly. 
Since the data source name has been there, we probably need to rename the .go file to align what the data source name is. With this adjustment, the check should be fixed.

**Review by chuyich — COMMENTED** [review]
Let me know if the PR is ready for reviewing.

**Comment by csahu9** [comment]
> Let me know if the PR is ready for reviewing.

Yes, I re-requested for review.

File: internal/provider/snapmirror/snapmirror_policy_resource.go [hunk 1]
```diff
@@ -298,30 +298,67 @@ func (r *SnapmirrorPolicyResource) Read(ctx context.Context, req resource.ReadRe
...
+					continue
+				}
+				configuredLabel := retention.Label.ValueString()
+				restItem, ok := restRetentionByLabel[configuredLabel]
+				if !ok {
+					data.Retention = append(data.Retention, retention)
+					continue
+				}
+				retention.Label = types.StringValue(restItem.Label)
+				if !retention.Count.IsNull() {
```
Comment (chuyich) [inline internal/provider/snapmirror/snapmirror_policy_resource.go:346]: Why only when !retention.Count.IsNull then allows to write the value back?

**Review by chuyich — CHANGES_REQUESTED** [review]
Check what I've mentioned regarding the document check. It could be fixed with the go file rename.
Also check the logic where I asked the question.

File: internal/provider/snapmirror/snapmirror_policy_resource.go (hunk 1 above)
Comment (csahu9) [reply internal/provider/snapmirror/snapmirror_policy_resource.go:346]: `retention.count` is Optional, so storing when valid value is returned and also to avoid error in the next step - `strconv.Atoi(restItem.Count)`.

**Review by chuyich — APPROVED** [review]

**Review by wenjun666 — APPROVED** [review]
