### PR TITLE
fixed v41_enable to modify when disabled instead of forcing resource replacement

### LINKED ISSUE #523: [Bug]: disabling nfs41 forces replacement
### Terraform Core Version

1.11.4

### ONTAP Provider Version

2.2.0

### Affected Resource(s)

* netapp-ontap_nfs_service.protocols_nfs_service

### Expected Behavior

if changing `v41_enabled = true` to `v41_enabled = false` NFS4.1 should simply be disabled like when executing `vserver nfs modify -vserver nfs-vserver -v4.1 disabled` 

### Actual Behavior
terraform deletes the whole vserver and recreates it
Image

### Terraform Configuration Files

```
terraform {
  required_providers {
    netapp-ontap = {
      source = "NetApp/netapp-ontap"
      version = "2.2.0"
    }
  }
}

locals {
  netapp-ip = ""
  netapp-user = ""
  netapp-pw = ""
  svm-name = ""
  aggr = ""
  v41_enabled = true
}

provider "netapp-ontap" {
  # A connection profile defines how to interface with an ONTAP cluster or svm.
  # At least one is required.
  connection_profiles = [
    {
      name = "cluster1"
      hostname = local.netapp-ip
      username = local.netapp-user
      password = local.netapp-pw
      validate_certs = false
    }
  ]
}

resource "netapp-ontap_svm" "example" {
  cx_profile_name = "cluster1"
  name = local.svm-name
  ipspace = "Default"
  snapshot_policy = "none"
  aggregates = [
    { name = local.aggr }
  ]
}

resource "netapp-ontap_nfs_service" "example" {
  cx_profile_name = "cluster1"
  svm_name = local.svm-name
  enabled = true
  protocol = {
    v3_enabled = true
    v40_enabled = false
    v41_enabled = local.v41_enabled
  }
  depends_on = [ netapp-ontap_svm.example ]
}


``` 

### Steps to Reproduce

fill out the local variables, do `terraform init` and `terraform apply` change `v41_enabled` to `false` and do `terraform apply`again

### PR DESCRIPTION
**Pull request by suhasbshekar**

### CODE REVIEW

File: internal/provider/protocols/protocols_nfs_service_resource.go [hunk 1]
```diff
@@ -873,7 +872,11 @@ func (r *ProtocolsNfsServiceResource) Update(ctx context.Context, req resource.U
 			errors = append(errors, "windows.v3_ms_dos_client_enabled")
 		}
 	}
-	request.SVM.Name = data.SVMName.ValueString()
+
+	// Field svm.name cannot be set in update operation when v41 is disabled.
```
Comment (wenjun666) [inline internal/provider/protocols/protocols_nfs_service_resource.go]: should this be part under line 787?

**Review by wenjun666 — APPROVED** [review]
