### PR TITLE
653 bug netapp ontap cifs sharetf cifs share0

### LINKED ISSUE #653: [Bug]: netapp-ontap_cifs_share.tf_cifs_share[0]:
### Terraform Core Version

v1.14.7

### ONTAP Provider Version

2.4.0

### Affected Resource(s)

netapp-ontap_cifs_share.tf_cifs_share[0]: Creating...
╷
│ Error: Provider returned invalid result object after apply
│ 
│ After the apply operation, the provider still indicated an unknown value for
│ netapp-ontap_cifs_share.tf_cifs_share[0].acls. All values must be known after apply, so
│ this is always a bug in the provider and should be reported in the provider's own
│ repository. Terraform will still save the other known object values in the state.

### Expected Behavior

CIFS share must be created.

### Actual Behavior

Got an error

### Relevant Error/Panic Output Snippet

```shell
netapp-ontap_cifs_share.tf_cifs_share[0]: Creating...
╷
│ Error: Provider returned invalid result object after apply
│ 
│ After the apply operation, the provider still indicated an unknown value for
│ netapp-ontap_cifs_share.tf_cifs_share[0].acls. All values must be known after apply, so
│ this is always a bug in the provider and should be reported in the provider's own
│ repository. Terraform will still save the other known object values in the state.
```

### Terraform Configuration Files

[06-cifs-local-group-privileges.zip](https://github.com/user-attachments/files/26398911/06-cifs-local-group-privileges.zip)

### Steps to Reproduce

run the above script

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by DhivyaBharathi215**
1. Fixed ACLs creation, now able to create empty list and can add n number of acls.
2. Fixed update issue with access based enumeration, as the values is always passed as false whenever update happens.

### CODE REVIEW

File: internal/provider/protocols/protocols_cifs_share_resource.go [hunk 1]
```diff
@@ -773,6 +790,14 @@ func (r *ProtocolsCIFSShareResource) Update(ctx context.Context, req resource.Up
 				resp.Diagnostics.Append(diags...)
 				return
 			}
+			// If plan has no ACLs at all, delete every state ACL directly.
```
Comment (chuyich) [inline internal/provider/protocols/protocols_cifs_share_resource.go]: Maybe put this logic out side of the for loop. It looks more clear.
if plan ACL == 0 means all the existing ACLs need to be removed.
else do the current for loop

**Review by chuyich — CHANGES_REQUESTED** [review]

File: internal/provider/protocols/protocols_cifs_share_resource.go [hunk 2]
```diff
@@ -765,46 +781,62 @@ func (r *ProtocolsCIFSShareResource) Update(ctx context.Context, req resource.Up
...
+				err = interfaces.DeleteProtocolsCIFSShareACL(errorHandler, *client, svm.UUID, plan.Name.ValueString(), stateACLElement.UserOrGroup, stateACLElement.Type)
+				if err != nil {
+					return
+				}
 			}
-			for index, planACL := range planeAcls {
-				var planACLElement ProtocolsCIFSShareResourceAcls
-				diags := planACL.As(ctx, &planACLElement, basetypes.ObjectAsOptions{})
+		}
+		if len(planeAcls) != 0 {
```
Comment (wenjun666) [inline internal/provider/protocols/protocols_cifs_share_resource.go]: use 'else' instead of 'if', as we there only two condtions len(planeAcls) == 0 or len(planeAcls) !=0

Comment (DhivyaBharathi215) [reply internal/provider/protocols/protocols_cifs_share_resource.go]: Modified

File: internal/provider/protocols/protocols_cifs_share_resource.go [hunk 3]
```diff
@@ -765,46 +781,61 @@ func (r *ProtocolsCIFSShareResource) Update(ctx context.Context, req resource.Up
...
 			return
 		}
-		// iterate over plan acls and compare with state acls. Make create or update or delete calls accordingly.
-		for _, element := range stateAcls {
-			var stateACLElement ProtocolsCIFSShareResourceAcls
-			diags := element.As(ctx, &stateACLElement, basetypes.ObjectAsOptions{})
-			if diags.HasError() {
-				resp.Diagnostics.Append(diags...)
-				return
+		if len(planeAcls) == 0 {
```
Comment (chuyich) [inline internal/provider/protocols/protocols_cifs_share_resource.go]: can you fix the typo 'planAcls' not 'planeAcls'? same as line 771

File: internal/provider/protocols/protocols_cifs_share_resource.go [hunk 4]
```diff
@@ -765,46 +781,61 @@ func (r *ProtocolsCIFSShareResource) Update(ctx context.Context, req resource.Up
...
-					if err != nil {
-						return
-					}
 
-				}
 			}
-
 		}
 		// now handle create action
 		for _, planACL := range planeAcls {
```
Comment (chuyich) [inline internal/provider/protocols/protocols_cifs_share_resource.go]: typo  'planeAcls'

**Review by chuyich — CHANGES_REQUESTED** [review]
please fix typo

**Review by wenjun666 — APPROVED** [review]

File: internal/provider/protocols/protocols_cifs_share_resource.go (hunk 4 above)
Comment (DhivyaBharathi215) [reply internal/provider/protocols/protocols_cifs_share_resource.go]: Modified

**Review by chuyich — APPROVED** [review]
