### PR TITLE
fix no entry issue

### LINKED ISSUE #659: [Enhancement]: cluster_peer resource ipspace entry not found
### Description

╷
│ Error: error creating cluster_peers
│ 
│   with netapp-ontap_cluster_peer.a_to_b,
│   on main.tf line 44, in resource "netapp-ontap_cluster_peer" "a_to_b":
│   44: resource "netapp-ontap_cluster_peer" "a_to_b" {
│ 
│ error on POST cluster/peers: GCNV API error 404 (NOT_FOUND): code: 404, message: {
│   "error":  {
│     "code":  "4",
│     "message":  "entry doesn't exist",
│     "target":  "uuid"
│   }
│ }, statusCode 404
╵

### Affected Resource(s) and/or Data Source(s)

_No response_

### Potential Terraform Configuration

```terraform

```

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by chuyich**

### CODE REVIEW

File: internal/interfaces/cluster_peer.go [hunk 1]
```diff
@@ -31,11 +31,11 @@ type ClusterPeersGetDataModelONTAP struct {
...
-	Name             string             `mapstructure:"name,omitempty"`
-	Remote           RemoteBody         `mapstructure:"remote"`
-	PeerApplications []string           `mapstructure:"peer_applications,omitempty"`
-	Authentication   Authentication     `mapstructure:"authentication"`
-	Ipspace          ClusterPeerIpspace `mapstructure:"ipspace,omitempty"`
+	Name             string              `mapstructure:"name,omitempty"`
+	Remote           RemoteBody          `mapstructure:"remote"`
+	PeerApplications []string            `mapstructure:"peer_applications,omitempty"`
+	Authentication   Authentication      `mapstructure:"authentication"`
+	Ipspace          *ClusterPeerIpspace `mapstructure:"ipspace,omitempty"`
```
Comment (wenjun666) [inline internal/interfaces/cluster_peer.go:38]: this need to use types.object
 Ipspace types.Object `tfsdk:"ipspace"`

**Review by wenjun666 — APPROVED** [review]
