### PR TITLE
Fixed provider produced inconsistent result after apply on privileges…

### LINKED ISSUE #458: [Docs]: typo in security_role resource document
### Documentation Link

https://github.com/NetApp/terraform-provider-netapp-ontap/blob/integration/main/docs/resources/security_roles.md

### Description

There is a typo 's' at the end of the resource name

all occurrences of security_roles needs to be replaced with security_role

also change the file name to security_role from security_roles

### References

_No response_

### Would you like to implement a fix?

None

### LINKED ISSUE #469: [Bug]: security role produces inconsistent result
### Terraform Core Version

1.7.1

### ONTAP Provider Version

2.1.0

### Affected Resource(s)

* netapp-ontap_security_role

### Expected Behavior

security role creates successfully 

### Actual Behavior

produces inconsistent 

### Relevant Error/Panic Output Snippet

```shell

```

### Terraform Configuration Files

resource "netapp-ontap_security_role" "security_role" {
  # required to know which system to interface with
 
  cx_profile_name = "cluster1"
  name            = "xx"
  svm_name        = "xx"
  privileges = [
    {
      access = "all"
      path   = "volume modify"
    }
  ]
}

### Steps to Reproduce

run the resources file.

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by wenjun666**
…. Fixed Documentation typo. Removed delting default privileges after create.

### CODE REVIEW

File: internal/provider/security/security_role_resource.go [hunk 1]
```diff
@@ -320,44 +351,32 @@ func (r *SecurityRoleResource) Create(ctx context.Context, req resource.CreateRe
 	// Priviledges
 	setElements := []attr.Value{}
 	for _, privilege := range restInfo.Privileges {
-		deleteDefaultPrivileges := false
-		if privilege.Path == "DEFAULT" && privilege.Access == "none" && privilege.Query == "" {
-			for _, planedPrivilege := range PrivilegesList {
```
Comment (suhasbshekar) [inline internal/provider/security/security_role_resource.go:325]: typo planedPrivilege-> plannedPrivilege

**Review by suhasbshekar — CHANGES_REQUESTED** [review]
Looking good, just a typo fix

**Review by suhasbshekar — APPROVED** [review]
