### PR TITLE
fix set acl error.

### LINKED ISSUE #236: [Bug]: unable to set CIFS ACL
### Terraform Core Version

1.5.7

### ONTAP Provider Version

1.1.2,1.1.1

### Affected Resource(s)

netapp-ontap_protocols_cifs_share_resource

### Expected Behavior

ACL should be set successfully

### Actual Behavior

Provider produces an error

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to netapp-ontap_protocols_cifs_share_resource.example, provider "provider[\"registry.terraform.io/netapp/netapp-ontap\"]" produced an unexpected new value: .acls: actual set element
│ cty.ObjectVal(map[string]cty.Value{"permission":cty.StringVal("full_control"), "type":cty.StringVal("windows"), "user_or_group":cty.StringVal("Everyone")}) does not correlate with any element in plan.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to netapp-ontap_protocols_cifs_share_resource.example, provider "provider[\"registry.terraform.io/netapp/netapp-ontap\"]" produced an unexpected new value: .acls: length changed from
│ 2 to 3.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

### Terraform Configuration Files

```
resource "netapp-ontap_storage_volume_resource" "example" {
  cx_profile_name = var.cluster
  name                = "example"
  svm_name       = data.netapp-ontap_svm_data_source.cifs.name
  aggregates      = "example"
  space = {
    size      = 1
    size_unit = "tb"
  }
  snapshot_policy = "none"
  nas = {
    security_style = "ntfs"
    junction_path  = "/example"
  }
}

resource "netapp-ontap_protocols_cifs_share_resource" "example" {
  cx_profile_name = var.cluster
  name            = "example"
  path            = "/example"
  svm_name        = data.netapp-ontap_svm_data_source.cifs.name
  acls = [
    {
      "permission" : "full_control",
      "type" : "windows",
      "user_or_group" : "mydomain\\myuser1"
    },
    {
      "permission" : "full_control",
      "type" : "windows",
      "user_or_group" : "mydomain\\myuser2"
    }
  ]
  comment = "Share for ${netapp-ontap_storage_volume_resource.example.name}"
}
```

### Steps to Reproduce

apply plan

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### LINKED ISSUE #257: [Bug]: Error creating share resource without everyone full_control acl
### Terraform Core Version

1.3.3

### ONTAP Provider Version

1.1.2

### Affected Resource(s)

netapp-ontap_protocols_cifs_share_resource

### Expected Behavior

Create a share with custom ACLs that do not include giving Everyone full_control.

### Actual Behavior

Error: Provider produced inconsistent result after apply
│
│ When applying changes to netapp-ontap_protocols_cifs_share_resource.share[0], provider "provider[\"registry.terraform.io/netapp/netapp-ontap\"]" produced an        
│ unexpected new value: .acls: actual set element cty.ObjectVal(map[string]cty.Value{"permission":cty.StringVal("full_control"), "type":cty.StringVal("windows"),     
│ "user_or_group":cty.StringVal("Everyone")}) does not correlate with any element in plan.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to netapp-ontap_protocols_cifs_share_resource.share[0], provider "provider[\"registry.terraform.io/netapp/netapp-ontap\"]" produced an        
│ unexpected new value: .acls: length changed from 2 to 3.

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

resource "netapp-ontap_protocols_cifs_share_resource" "share" {
  count = var.nas_type == "smb" ? 1 : 0
  cx_profile_name = var.storage_tier
  name = var.share_name
  path = netapp-ontap_storage_volume_resource.volume.nas.junction_path
  svm_name = local.svm_name
  acls = [{
        "permission": "full_control",
        "type": "windows",
        "user_or_group": "user@domain"
    },
    {
        "permission": "change",
        "type": "windows",
        "user_or_group": "group@domain"
    }]
}

### Steps to Reproduce

create share

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by wenjun666**

### CODE REVIEW

File: internal/provider/protocols_cifs_share_resource_test.go [hunk 1]
```diff
@@ -50,9 +62,12 @@ func TestAccProtocolsCIFSShareResource(t *testing.T) {
...
 func testAccProtocolsCIFSShareResourceConfig(svm, shareName string) string {
-	host := os.Getenv("TF_ACC_NETAPP_HOST_CIFS")
-	admin := os.Getenv("TF_ACC_NETAPP_USER")
-	password := os.Getenv("TF_ACC_NETAPP_PASS2")
+	// host := os.Getenv("TF_ACC_NETAPP_HOST_CIFS")
+	// admin := os.Getenv("TF_ACC_NETAPP_USER")
+	// password := os.Getenv("TF_ACC_NETAPP_PASS2")
+	host := "10.193.73.2"
+	admin := "admin"
+	password := "Netapp1!"
```
Comment (carchi8py) [inline internal/provider/protocols_cifs_share_resource_test.go]: you need to remove the Host, username, and password and use one of the TF variable. If we need new one let me know.

File: internal/provider/protocols_cifs_share_resource_test.go [hunk 2]
```diff
@@ -80,17 +95,109 @@ resource "netapp-ontap_protocols_cifs_share_resource" "example" {
...
 func testAccProtocolsCIFSShareResourceConfigUpdate(svm, volName string) string {
-	host := os.Getenv("TF_ACC_NETAPP_HOST_CIFS")
-	admin := os.Getenv("TF_ACC_NETAPP_USER")
-	password := os.Getenv("TF_ACC_NETAPP_PASS2")
+	// host := os.Getenv("TF_ACC_NETAPP_HOST_CIFS")
+	// admin := os.Getenv("TF_ACC_NETAPP_USER")
+	// password := os.Getenv("TF_ACC_NETAPP_PASS2")
+	host := "10.193.73.2"
+	admin := "admin"
+	password := "Netapp1!"
```
Comment (carchi8py) [inline internal/provider/protocols_cifs_share_resource_test.go]: Remove

File: internal/provider/protocols_cifs_share_resource_test.go [hunk 3]
```diff
@@ -80,17 +95,109 @@ resource "netapp-ontap_protocols_cifs_share_resource" "example" {
...
+}`, host, admin, password, volName, svm)
+}
+
+func testAccProtocolsCIFSShareResourceConfigUpdateAddACL(svm, volName string) string {
+	// host := os.Getenv("TF_ACC_NETAPP_HOST_CIFS")
+	// admin := os.Getenv("TF_ACC_NETAPP_USER")
+	// password := os.Getenv("TF_ACC_NETAPP_PASS2")
+	host := "10.193.73.2"
+	admin := "admin"
+	password := "Netapp1!"
```
Comment (carchi8py) [inline internal/provider/protocols_cifs_share_resource_test.go]: Remove

File: internal/provider/protocols_cifs_share_resource_test.go [hunk 4]
```diff
@@ -80,17 +95,109 @@ resource "netapp-ontap_protocols_cifs_share_resource" "example" {
...
+}`, host, admin, password, volName, svm)
+}
+
+func testAccProtocolsCIFSShareResourceConfigUpdateDeleteACL(svm, volName string) string {
+	// host := os.Getenv("TF_ACC_NETAPP_HOST_CIFS")
+	// admin := os.Getenv("TF_ACC_NETAPP_USER")
+	// password := os.Getenv("TF_ACC_NETAPP_PASS2")
+	host := "10.193.73.2"
+	admin := "admin"
+	password := "Netapp1!"
```
Comment (carchi8py) [inline internal/provider/protocols_cifs_share_resource_test.go]: Remove

**Review by carchi8py — CHANGES_REQUESTED** [review]

**Review by carchi8py — APPROVED** [review]
