### PR TITLE
fix: allow unlocking existing `security_account` resources

### LINKED ISSUE #499: [Bug]: unable to unlock existing `security_account` resource
### Terraform Core Version

1.12.0

### ONTAP Provider Version

2.2.0

### Affected Resource(s)

* netapp-ontap_security_account

### Expected Behavior

It should be possible to unlock a locked security account, by setting the `locked` attribute to `false`.

### Actual Behavior

Setting the `locked` attribute of an existing security account to `false` leads to an error.

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ netapp-ontap_security_account.security_account, provider
│ "provider[\"registry.terraform.io/netapp/netapp-ontap\"]" produced an
│ unexpected new value: .locked: was cty.False, but now cty.True.
│ 
│ This is a bug in the provider, which should be reported in the
│ provider's own issue tracker.
╵
```

### Terraform Configuration Files

```terraform
resource "netapp-ontap_security_account" "security_account" {
  # required to know which system to interface with
  cx_profile_name = "cluster4"
  name            = "carchitest"
  applications = [{
    application            = "http"
    authentication_methods = ["password"]
  }]
  password = "P@ssw0rd"
  locked   = false
}
```

### Steps to Reproduce

1. Set `resource "netapp-ontap_security_account" { locked = true }` in the configuration.
2. `terraform apply -auto-approve`
3. Change the configuration to `locked = false`.
4. `terraform apply -auto-approve`

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by acch**
Fixes #499.

When unlocking existing, locked security accounts, Terraform produces the following error:

```shell
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ netapp-ontap_security_account.security_account, provider
│ "provider[\"registry.terraform.io/netapp/netapp-ontap\"]" produced an
│ unexpected new value: .locked: was cty.False, but now cty.True.
│ 
│ This is a bug in the provider, which should be reported in the
│ provider's own issue tracker.
╵
```

This PR changes the internal data type of the `locked` attribute to bool pointer, to allow for three distinct values:
- null / undefined (-> omit attribute in REST call)
- true (-> lock account)
- false (-> unlock account)

ACC tests pass:

```shell
$ TF_ACC=1 go test ./internal/provider/security/security_account_resource_test.go -v
=== RUN   TestAccSecurityAccountResource
--- PASS: TestAccSecurityAccountResource (7.98s)
PASS
ok      command-line-arguments  7.988s
```

### CODE REVIEW

File: internal/provider/security/security_account_resource.go [hunk 1]
```diff
@@ -410,6 +406,7 @@ func (r *SecurityAccountResource) Create(ctx context.Context, req resource.Creat
 
 	data.ID = types.StringValue(resource.Name)
 	data.OwnerID = types.StringValue(resource.Owner.UUID)
+	data.Locked = types.BoolValue(resource.Locked)
```
Comment (csahu9) [inline internal/provider/security/security_account_resource.go:409]: Shouldn't this be `types.BoolPointerValue`?

Comment (acch) [reply internal/provider/security/security_account_resource.go:409]: No.

`data` is a `*SecurityAccountResourceModel` (Terraform Type), defined [here](https://github.com/acch/terraform-provider-netapp-ontap/blob/6f631cd248faca3e9681844ce12549f3773be675/internal/provider/security/security_account_resource.go#L52). `data.Locked` is type `types.Bool`, so we're assigning `types.BoolValue()` here.

In [Line 345](https://github.com/acch/terraform-provider-netapp-ontap/blob/6f631cd248faca3e9681844ce12549f3773be675/internal/provider/security/security_account_resource.go#L345) we're dealing with `body`, which is a `interfaces.SecurityAccountResourceBodyDataModelONTAP` (ONTAP Type), defined [here](https://github.com/acch/terraform-provider-netapp-ontap/blob/6f631cd248faca3e9681844ce12549f3773be675/internal/interfaces/security_account.go#L13). `body.Locked` is type `*bool`, so in Line 345 we're assigning `data.Locked.ValueBoolPointer()`.

Does this make sense?

**Review by suhasbshekar — APPROVED** [review]
